# Site settings
title: Tatiana Gavrilova
description: "Tatiana Gavrilova, språklærer"
email: me@TatianaGavrilova.com
phone: (+47) 40728906
address: "Trondheim, Norge"
orgnumber: 914115183
baseurl: ""
name: TatianaGavrilova.com
url: "http://TatianaGavrilova.com"
i18n-lang-name: Norsk
i18n-menu-home: Hjem
i18n:
  en:
    name: English
    home: Home

# Build settings
markdown: kramdown
